swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "city"
  description: "Operations about city"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /api/v1/citys:
    post:
      tags:
      - "city"
      summary: "Create city"
      description: "This can only be done by the logged in city."
      operationId: "createcity"
      produces:
      # - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        required: true        
        description: "Only admin can load and config this page"

      - in: "body"
        name: "body"
        description: "Created city object"
        required: true
        schema:
          $ref: "#/definitions/city_no_id"
      responses:
        "200":
          description: "create successfull"
          schema:
            $ref: '#/definitions/ApiResponse'            
        "400":
          description: "fail create "
          schema:
            $ref: '#/definitions/ApiResponse'            
    get:
      tags:
      - "city"
      summary: "get all city"
      description: ""
      operationId: "logoutcity"
      produces:
      # - "application/xml"
      - "application/json"
      parameters: []

      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:            
              $ref: "#/definitions/city"
          # headers:
          #   X-Rate-Limit:
          #     type: "integer"
          #     format: "int32"
          #     description: "calls per hour allowed by the city"
          #   X-Expires-After:
          #     type: "string"
          #     format: "date-time"
          #     description: "date in UTC when token expires"
        "400":
          description: "Bad request"
          schema:
            $ref: '#/definitions/ApiResponse'          
  
  /api/v1/citys/{id}:
    get:
      tags:
      - "city"
      summary: "Get city by id name"
      description: ""
      operationId: "getcityByName"
      produces:
      # - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        required: true        
        description: "Only admin can load and config this page"

      - name: "id"
        in: "path"
        description: "The name that needs to be fetched. Use city1 for testing. "
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/city"
        "400":
          description: "Bad request"
          schema:
            $ref: '#/definitions/ApiResponse'            
        "401":
          description: "Authorization requirement"
          schema:
            $ref: '#/definitions/ApiResponse'            

    put:
      tags:
      - "city"
      summary: "Updated city"
      description: "This can only be done by the logged in city."
      operationId: "updatecity"
      produces:
      # - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        required: true        
        description: "Only admin can load and config this page"
        
      - name: "id"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated city object"
        required: true
        schema:
          $ref: "#/definitions/city_no_id"
      responses:
        "200":
          description: "successfull"
          schema:
            $ref: '#/definitions/ApiResponse'          
        "400":
          description: "Bad request"
          schema:
            $ref: '#/definitions/ApiResponse'            
        "401":
          description: "Authorization requirement"
          schema:
            $ref: '#/definitions/ApiResponse'            

    delete:
      tags:
      - "city"
      summary: "Delete city"
      description: "This can only be done by the logged in city."
      operationId: "deletecity"
      produces:
      # - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        required: true
        description: "Only admin can load and config this page"

      - name: "id"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"

      responses:
        "200":
          description: "successfull"
          schema:
            $ref: '#/definitions/ApiResponse'         
        "400":
          description: "Bad request"
          schema:
            $ref: '#/definitions/ApiResponse'            
        "401":
          description: "Authorization requirement"
          schema:
            $ref: '#/definitions/ApiResponse'            


securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:
  city:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"      
      name:
        type: "string"
        example: "Da nang"
      code:
        type: "string"
        example: "Danang"
    xml:
      name: "city"
  city_no_id:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Da nang"
      code:
        type: "string"
        example: "Danang"
    xml:
      name: "city"

  ApiResponse:
    type: "object"
    properties:
      message:
        type: "string"
        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"