swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "role_cam_user"
  description: "Operations about role_cam_user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /api/v1/role_cam_user:
    post:
      tags:
      - "role_cam_user"
      summary: "Create role_cam_user"
      # description: "This can only be done by the logged in user."
      operationId: "createUser"
      produces:
      # - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        required: true        
        description: "Only admin can load and config this page"

      - in: "body"
        name: "body"
        description: "Created object"
        required: true
        schema:
          $ref: "#/definitions/role_cam_user_no_id"
      responses:
        "200":
          description: " create successfull"
          schema:
            $ref: '#/definitions/ApiResponse'            
        "400":
          description: "fail create"
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      tags:
      - "role_cam_user"
      summary: "get all role_cam_user"
      description: ""
      operationId: "logoutUser"
      produces:
      # - "application/xml"
      - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          required: true        
          description: "Only admin can load and config this page"
        - in: query
          name: user_id
          type: integer
          required: false
          description: Load config by user
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:            
              $ref: "#/definitions/role_cam_user"
          # headers:
          #   X-Rate-Limit:
          #     type: "integer"
          #     format: "int32"
          #     description: "calls per hour allowed by the user"
          #   X-Expires-After:
          #     type: "string"
          #     format: "date-time"
          #     description: "date in UTC when token expires"
        "400":
          description: "Bad request"
          schema:
            $ref: '#/definitions/ApiResponse'          
  
  /api/v1/role_cam_user/{id}:
    get:
      tags:
      - "role_cam_user"
      summary: "Get role_cam_user by id name"
      description: ""
      operationId: "getUserByName"
      produces:
      # - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        required: true        
        description: "Only admin can load and config this page"

      - name: "id"
        in: "path"
        description: "The name that needs to be fetched. Use user1 for testing. "
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/role_cam_user"
        "400":
          description: "Bad request"
          schema:
            $ref: '#/definitions/ApiResponse'          
        "401":
          description: "Authorization requirement"
          schema:
            $ref: '#/definitions/ApiResponse'          

    put:
      tags:
      - "role_cam_user"
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
      produces:
      # - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        required: true        
        description: "Only admin can load and config this page"
        
      - name: "id"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/role_cam_user_no_id"
      responses:
        "200":
          description: "successfull"
          schema:
            $ref: '#/definitions/ApiResponse'          
        "400":
          description: "Bad request"
          schema:
            $ref: '#/definitions/ApiResponse'          
        "401":
          description: "Authorization requirement"
          schema:
            $ref: '#/definitions/ApiResponse'          

    delete:
      tags:
      - "role_cam_user"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "deleteUser"
      produces:
      # - "application/xml"
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        type: "string"
        required: true
        description: "Only admin can load and config this page"

      - name: "id"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"

      responses:
        "200":
          description: "successfull"
          schema:
            $ref: '#/definitions/ApiResponse'         
        "400":
          description: "Bad request"
          schema:
            $ref: '#/definitions/ApiResponse'          
        "401":
          description: "Authorization requirement"
          schema:
            $ref: '#/definitions/ApiResponse'          


securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"

definitions:
  role_cam_user:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"          
        bus_user_id:
        type: "integer"
        format: "int32"  
      bus_camera_id:
        type: "integer"
        format: "int32"
        bus_user_name:
          type: "string"
        bus_camera_name:
          type: "string"
          
    xml:
      name: "role_cam_user"
  

  role_cam_user_no_id:
    type: "object"
    properties:
      update_user_id:
        type: "integer"
        format: "int32"  
      bus_cameras:
        type: "array"
        items: 
          type: "object"
          properties:
            id:
              type: "integer"
              format: "int32"          
            bus_camera_id:
              type: "integer"
              format: "int32"
            delete:
              type: "boolean"
              format: "int32"
        example:
          - id: 10
            bus_camera_id: 1
            delete: true
          - id: 11
            bus_camera_id: 2
            delete: false
          - id: 12
            bus_camera_id: 3
          - id: null
            bus_camera_id: 4
    xml:
      name: "role_cam_user_no_id"

  ApiResponse:
    type: "object"
    properties:
      message:
        type: "string"
        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"